### PR TITLE
Fix master build

### PR DESCRIPTION
**Pull request by svyatonik**
https://gitlab.parity.io/parity/mirrors/parity-bridges-common/-/jobs/4024579

Just a [partial copy](https://github.com/paritytech/parity-bridges-common/blob/polkadot-staging/primitives/xcm-bridge-hub-router/src/lib.rs) of required files from `polkadot-staging`.

### CODE REVIEW

**Review by bkontur — APPROVED** [review]
hmm, just wondering how could have [this](https://github.com/paritytech/parity-bridges-common/pull/2638) passed without this yesterday?

**Comment by svyatonik** [comment]
I think because asset hub primitives are missing from our top-level `Cargo.toml`. Do you think we need to add it there, @bkontur ?

**Comment by svyatonik** [comment]
Actually, let's do it :)

**Comment by bkontur** [comment]
> hmm, just wondering how could have [this](https://github.com/paritytech/parity-bridges-common/pull/2638) passed without this yesterday?

I see, nighlty pipeline for chain primitives, which we dont reference here in bridges repo,
also we forgot to add them to the main Cargo.toml

**Comment by bkontur** [comment]
yes, lets better add them (also to polkadot-staging)

**Comment by svyatonik** [comment]
> yes, lets better add them (also to polkadot-staging)

:+1: done

**Pull request merged**
