### PR TITLE
Fix Rialto test-poa genesis state root

### PR DESCRIPTION
**Pull request by svyatonik**
this should (hopefully) fix the deployment issue

### CODE REVIEW

**Comment by tomusdrw** [comment]
Ah, it's related to #347? Is there a way we can prevent this in the future?
Maybe a tool to generate ETH genesis hash based on the chainspec?

**Review by tomusdrw — APPROVED** [review]

**Comment by svyatonik** [comment]
I think the feature we need is "comments-in-json" :)

**Comment by HCastano** [comment]
I thought #347 was pretty trivial, didn't realize it would break our deployment upon merging, whoops!

@svyatonik how did you get the new `state_root`?

**Review by HCastano — APPROVED** [review]

**Comment by svyatonik** [comment]
By starting PoA node && calling RPC

**Pull request merged**
