### PR TITLE
Renamings

### PR DESCRIPTION
**Pull request by serban300**
StorageProofSize -> StorageSize
receive_single_message_n_bytes_proof -> receive_single_n_bytes_message_proof
receive_single_message_n_bytes_proof_with_dispatch -> receive_single_n_bytes_message_proof_with_dispatch

Related to #2212

### CODE REVIEW

**Review by svyatonik — APPROVED** [review]
Since you're going to fill up trie somewhere else, maybe it worth removing `enum StorageSize` at all? Like we'll only care about the message (aka leaf) size in currently existing code, right? And your trie-fill-code will be always running after the minimal trie is built?

**Comment by svyatonik** [comment]
> Either we'll always fill the minimal trie with a hardcoded number of common-prefixes. Or we should have a benchmark for the proof size. Not sure what would be best. But anyway, I think we need to take into account the size of the storage (leafs) as well. Because it impacts the weight. So I think we should keep the StorageSize enum.

True. I mean - we leave `StorageSize`, but it'll be just `u32` - i.e. leaf/message size :)

**Comment by svyatonik** [comment]
(I mean it's just my opinion - feel free to leave as is)

**Comment by serban300** [comment]
> > Either we'll always fill the minimal trie with a hardcoded number of common-prefixes. Or we should have a benchmark for the proof size. Not sure what would be best. But anyway, I think we need to take into account the size of the storage (leafs) as well. Because it impacts the weight. So I think we should keep the StorageSize enum.
> 
> True. I mean - we leave `StorageSize`, but it'll be just `u32` - i.e. leaf/message size :)

Oh, you might be right. Looking into it.

**Review by svyatonik — APPROVED** [review]
:+1:

**Review by acatangiu — APPROVED** [review]

**Pull request merged**
