### PR TITLE
Drop Rialto <> Millau bridges

### PR DESCRIPTION
**Pull request by svyatonik**
We already have some troubles with maintaining those bridges (https://github.com/paritytech/parity-bridges-common/pull/2647#pullrequestreview-1703849299).

Since we already have a live setup (Rococo <> Wococo), which will be superseded with [Rococo <> Westend](https://github.com/paritytech/parity-bridges-common/pull/2647) bridge soon AND at least we have [some basic zombienet tests](https://github.com/paritytech/parity-bridges-common/pull/2660), I think the time has come to drop Rialto and Millau (and test deployments VM).

Couple of things to mention:
- also removed several unused subcommands of `substrate-relay` binary;
- also removed several scripts that will be unneeded after we'll move to `polkadot-sdk`;
- also removed fuzzer that has never been used;
- left the only docker image that should be built from this repo - the one with `substrate-relay` binary. We'll need to have a similar build step in `polkadot-sdk`, but until that, we'll be building it from here.

### CODE REVIEW

**Review by bkontur — APPROVED** [review]
@svyatonik Slava, you should write some condolence speech for Millau and Rialto :(,
Maybe I asked that before, but who and why did choose those names?

Will do the same for `polkadot-staging?

**Comment by svyatonik** [comment]
> @svyatonik Slava, you should write some condolence speech for Millau and Rialto :(, Maybe I asked that before, but who and why did choose those names?
> 
> Will do the same for `polkadot-staging?

Let's just move forward with that. I think @tomusdrw was behind that :) Just some bridges (https://en.wikipedia.org/wiki/Rialto_Bridge + https://en.wikipedia.org/wiki/Millau_Viaduct)

**Review by sergejparity — APPROVED** [review]

**Review by acatangiu — APPROVED** [review]
40K lines fewer to maintain ❤️

**Comment by tomusdrw** [comment]
> > @svyatonik Slava, you should write some condolence speech for Millau and Rialto :(, Maybe I asked that before, but who and why did choose those names?
> > Will do the same for `polkadot-staging?
> 
> Let's just move forward with that. I think @tomusdrw was behind that :) Just some bridges (https://en.wikipedia.org/wiki/Rialto_Bridge + https://en.wikipedia.org/wiki/Millau_Viaduct)

Indeed :)

**Pull request merged**
