### PR TITLE
Try check-rustdoc pipeline

### PR DESCRIPTION
**Pull request by bkontur**
if we put bridges repo as subtree to Cumulus,
then Cumulus CI is failing like here: https://github.com/paritytech/parity-bridges-common/pull/1782,
so I am trying here to setup the same job here to prevent this

### CODE REVIEW

**Comment by bkontur** [comment]
bot rebase

**Review by acatangiu — APPROVED** [review]

**Comment by acatangiu** [comment]
Check seems to be working. Now you have to also fix the doc errors it throws 😄

**Comment by bkontur** [comment]
> Check seems to be working. Now you have to also fix the doc errors it throws smile

yes, yes, exactly, thats the reason, because if we subtree this to the cumulus, cumulus fails, 
and finally https://github.com/paritytech/cumulus/pull/2111 everything works (tests, benchmarks, try-rutime), this doc stuff is the last

**Review by sergejparity — APPROVED** [review]

**Comment by bkontur** [comment]
bot rebase

**Pull request merged**
