### PR TITLE
Monitoring and alerts for Rococo/Westend

### PR DESCRIPTION
**Pull request by bkontur**
- [x] copy rococo-wococo -> rococo-westend and rename Wococo -> Westend
- [x] remove rococo-wococo
- [x] clean beefy stuff out of rococo-westend folder
- [x] deploy with DevOps: https://grafana.teleport.parity.io/dashboards/f/eblDiw17z/bridges

### CODE REVIEW

**Review by svyatonik — COMMENTED** [review]
I think the lane 00000001 must also be changed to 00000002

**Comment by svyatonik** [comment]
also if we're planning to do import to Grafana, then perhaps we should remove R<>Wococo dashboards/alerts first - I wonder how Grafana would solve IDs conflicts during import

**Comment by bkontur** [comment]
- [ ] for Rococo BEEFY alerts change matrix room: `!lMunCqbBqxEqfRuUDF:parity.io` -> `lMunCqbBqxEqfRuUDF`

**Review by svyatonik — APPROVED** [review]
Thank you!

**Pull request merged**
