### PR TITLE
Migrate to Polkadot v1.0.0 Dependency

### PR DESCRIPTION
**Pull request by asiniscalchi**
#### Summary

This PR aims to migrate `parity-bridges-common` from a dependency on Polkadot's `master` branch to the stable `v1.0.0`. This change will resolve dependency conflicts for projects that aim to integrate this library.

#### Changes

- Updated `Cargo.toml` to specify Polkadot v1.0.0 dependency.
- Modified code to adapt to Polkadot v1.0.0 API changes.

#### Impact

- Easier dependency management.
- Increased stability and reliability for downstream projects.

Please let me know of any concerns or changes needed. Thank you.

### CODE REVIEW

**Comment by svyatonik** [comment]
@asiniscalchi Thank you for doing this job! WDYT about having a dedicated branch for that? We could add `polkadot-1.0` branch and merge your commits there. However, we probably do not want to have this in a `master`, wdyt @acatangiu @bkchr @serban300 ? That's because we may need to update our code to work with [`polkadot-sdk` master](https://github.com/paritytech/polkadot-sdk) - the simplest case would be backporting changes from [`polkadot-sdk` bridges subtree](https://github.com/paritytech/polkadot-sdk/tree/master/cumulus/bridges).

(*sharing some our thoughts*) In the future we will probably migrate all essential bridges functionality (pallets, primitives) to `polkadot-sdk`. Other code (relayers) will be either migrated too, or will live here.

**Comment by asiniscalchi** [comment]
> @asiniscalchi Thank you for doing this job! WDYT about having a dedicated branch for that? We could add `polkadot-1.0` branch and merge your commits there. However, we probably do not want to have this in a `master`, wdyt @acatangiu @bkchr @serban300 ? That's because we may need to update our code to work with [`polkadot-sdk` master](https://github.com/paritytech/polkadot-sdk) - the simplest case would be backporting changes from [`polkadot-sdk` bridges subtree](https://github.com/paritytech/polkadot-sdk/tree/master/cumulus/bridges).
> 
> (_sharing some our thoughts_) In the future we will probably migrate all essential bridges functionality (pallets, primitives) to `polkadot-sdk`. Other code (relayers) will be either migrated too, or will live here.

Having a `polkadot-v1.0.0` branch seems the _way to go_ in the substrate ecosystem. So by my side is a GO.
Thanks

**Comment by acatangiu** [comment]
> We could add polkadot-1.0 branch and merge your commits there.

Yes, this is the way to go. 👍

**Comment by svyatonik** [comment]
@asiniscalchi I've added the [`polkadot-v1.0` branch](https://github.com/paritytech/parity-bridges-common/tree/polkadot-v1.0), forked off current master. Could you, please, change the base branch for this PR (and fix conflicts if there are any). We will finish review once it is done. Thank you!

**Comment by asiniscalchi** [comment]
however I suggest to use `polkadot-v1.0.0` to be consistent with other projects

**Comment by svyatonik** [comment]
> however I suggest to use `polkadot-v1.0.0` to be consistent with other projects

True, sorry for that! Renamed the base branch to `polkadot-v1.0.0`. Can you, please, reopen/recreate the PR?

**Pull request closed without merging**
