### PR TITLE
Polkadot staging update

### PR DESCRIPTION
**Pull request by svyatonik**
(polkadot-staging will be used to tag substrate-relay 1.0 => push substrate-relay 1.0 image)

Will need to be sure that there are no differences between `master` and updated `polkadot-staging` - will update description with results.

UPD:
```bash
svyatonik@xwnotebook:~/dev$ git clone --depth 1 -b master https://github.com/paritytech/parity-bridges-common.git parity-bridges-common-master
Cloning into 'parity-bridges-common-master'...
remote: Enumerating objects: 455, done.
remote: Counting objects: 100% (455/455), done.
remote: Compressing objects: 100% (392/392), done.
remote: Total 455 (delta 113), reused 209 (delta 33), pack-reused 0
Receiving objects: 100% (455/455), 581.24 KiB | 903.00 KiB/s, done.
Resolving deltas: 100% (113/113), done.
Checking connectivity... done.
svyatonik@xwnotebook:~/dev$ git clone --depth 1 -b polkadot-staging-update https://github.com/paritytech/parity-bridges-common.git parity-bridges-common-polkadot-staging-update
Cloning into 'parity-bridges-common-polkadot-staging-update'...
remote: Enumerating objects: 455, done.
remote: Counting objects: 100% (455/455), done.
remote: Compressing objects: 100% (392/392), done.
remote: Total 455 (delta 113), reused 209 (delta 33), pack-reused 0
Receiving objects: 100% (455/455), 580.91 KiB | 0 bytes/s, done.
Resolving deltas: 100% (113/113), done.
Checking connectivity... done.
svyatonik@xwnotebook:~/dev$ diff --exclude .git -qr parity-bridges-common-master parity-bridges-common-polkadot-staging-update
svyatonik@xwnotebook:~/dev$ 
```

### CODE REVIEW

**Review by acatangiu — APPROVED** [review]
The update looks good, but I don't get why we're doing it now. The process is still unclear to me :smiling_face_with_tear:

**Comment by acatangiu** [comment]
> The update looks good, but I don't get why we're doing it now. The process is still unclear to me smiling_face_with_tear

Nevermind, this is good, I thought the update is the other way around! :+1:

**Comment by svyatonik** [comment]
Yeah - still not clear to me as well :) I just was going to publish `substrate-relay` image (to use in Rococo <> Wococo bridge) and I was thinking that it'd be better to tag some commit in our release branch.

**Comment by svyatonik** [comment]
Oh, I'm dumb :confused:  - this is `polkadot-staging` to `master` PR. Should be opposite - will reopen :)

**Pull request closed without merging**
