### PR TITLE
Reuse polkadot-service code

### LINKED ISSUE #1136: Try to reuse polkadot service code
https://github.com/paritytech/parity-bridges-common/pull/1053 brings introduces some code that is copypasted from polkadot service. Thanks to @ordian we now have this - https://github.com/paritytech/polkadot/pull/3820 && may try to reuse existing code. However, I prefer to do that until Rialto will be running as relay chain && there's (at least) dummy parachain registered there (basically - what we have in [this](https://github.com/paritytech/parity-bridges-common/tree/rialto-as-relay-chain) branch).

### PR DESCRIPTION
**Pull request by svyatonik**
closes #1136 

Unfortunately, `polkadot-runtime` is still requires `polkadot-service` (actually - one of P/K/W/R runtimes is now required - I've selected polkadot). If it isn't selected, no runtime-features of `polkadot-client` are activated and I'm getting [this error](https://github.com/paritytech/polkadot/blob/master/node/client/src/lib.rs#L49).

But at least I've been able to reuse `polkadot-service` and remove our custom `service.rs`, `overseer.rs` and `parachains_db.rs` (which is a lot of code).

### CODE REVIEW

**Comment by svyatonik** [comment]
on hold, until I'll solve https://github.com/paritytech/parity-bridges-common/issues/1268#issuecomment-1000768074

**Comment by acatangiu** [comment]
looks like this is unblocked now

**Comment by svyatonik** [comment]
Yeah - it is ready for review :)

**Review by acatangiu — APPROVED** [review]
:100:

**Pull request merged**
