### PR TITLE
Get substrate dependencies from crates io

### LINKED ISSUE #20: Update Substrate dependencies to use crates.io versions
With the v2.0 freeze that happened in Substrate today we'll hopefully be seeing a lot of crates get published to crates.io soon. We'll need to update our dependencies to use that instead of pulling from git.

### PR DESCRIPTION
**Pull request by svyatonik**
closes #20 

The only drawback is that we're losing single test, which was testing that the message-lane RPCs are actually generating verifiable storage proofs. I was unable to take `substrate-test-runtime-client` crate from git + all others from crates.io.

### CODE REVIEW

**Review by tomusdrw — APPROVED** [review]
:tada:

**Comment by svyatonik** [comment]
Looks like this update breaks our metrics + alerts => I'll try to find why

**Comment by svyatonik** [comment]
Looks like some temp local issue

**Comment by HCastano** [comment]
Cool! @svyatonik did you use a script, or do this manually?

**Comment by svyatonik** [comment]
Manually :) We need to do that only once, right?

**Pull request merged**
