### PR TITLE
Fix OutboundLaneData types

### PR DESCRIPTION
**Pull request by HackFisher**
Related https://github.com/darwinia-network/apps/issues/277#issuecomment-926319423

Reference: https://github.com/darwinia-network/parity-bridges-common/blob/7be2b478b49bc8e87ddfe034076e9e80e2f126f6/primitives/messages/src/lib.rs#L278-L287

### CODE REVIEW

**Review by tomusdrw — APPROVED** [review]
Thanks! These types should not be necessary (see #1140) and the main fix should be in `polkadot.js/api`. Did you make a PR there already?

Let's merge this PR as well though, since it can serve as an override.

**Comment by HackFisher** [comment]
Also made a PR to `polkadot.js/api` just now: https://github.com/polkadot-js/api/pull/3992

**Comment by tomusdrw** [comment]
Awesome, thanks a lot!!!

**Review by tomusdrw — CHANGES_REQUESTED** [review]
Actually, please update `common.json` file and run `build.sh` to regenerate the types properly, I just noticed it's missing from there.

**Review by tomusdrw — APPROVED** [review]

**Pull request merged**
