### PR TITLE
Update types to contain dispatch_fee_payment

### PR DESCRIPTION
**Pull request by tomusdrw**
CC @hbulgarini

### CODE REVIEW

**Comment by hbulgarini** [comment]
@tomusdrw  what's the purpose of these new `dispatch_fee_payment` types? is this change transparent for the the state call that we perform on the UI?

**Comment by tomusdrw** [comment]
It's for this feature: https://github.com/paritytech/parity-bridges-common/issues/561.
Something that we might want to implement in the UI somewhere in the (mid) future.

**Comment by hbulgarini** [comment]
> It's for this feature: #561.
> Something that we might want to implement in the UI somewhere in the (mid) future.

Looks good to me, even if i'm not set as approver, you can go ahead with the merge.

**Review by HCastano — APPROVED** [review]

**Comment by HCastano** [comment]
@hbulgarini you should be able to approve and merge PRs

**Pull request merged**
