### PR TITLE
Use same fmt and clippy configs as in Polkadot/Cumulus

### PR DESCRIPTION
**Pull request by bkontur**
Lets see if it works

Closes: https://github.com/paritytech/parity-bridges-common/issues/2383

### CODE REVIEW

**Review by serban300 — APPROVED** [review]

**Comment by bkontur** [comment]
@svyatonik Slava, where do we need to install this?
```
error: 'cargo-clippy' is not installed for the toolchain 'stable-x86_64-unknown-linux-gnu'
```

**Comment by serban300** [comment]
> @svyatonik Slava, where do we need to install this?
> 
> ```
> error: 'cargo-clippy' is not installed for the toolchain 'stable-x86_64-unknown-linux-gnu'
> ```

Probably here: https://github.com/paritytech/scripts/blob/master/dockerfiles/bridges-ci/Dockerfile

**Comment by bkontur** [comment]
https://github.com/paritytech/scripts/pull/591

**Review by sergejparity — APPROVED** [review]

**Review by acatangiu — APPROVED** [review]
let's rebase and try it

**Comment by bkontur** [comment]
Closing in favor of https://github.com/paritytech/parity-bridges-common/pull/2746

**Pull request closed without merging**
