### PR TITLE
Fix updated clippy grumbles

### PR DESCRIPTION
**Pull request by svyatonik**
this is reincarnation of #732 (force-pushed => can't reopen that other PR)
I've also reverted pinning of nightly version here

### CODE REVIEW

**Review by tomusdrw — APPROVED** [review]

**Review by adoerr — COMMENTED** [review]
Running `clippy` locally gives me the following error:

image

Any ideas?

**Comment by svyatonik** [comment]
`rustup update` shall help - see #652

**Comment by adoerr** [comment]
Nope. Ran `rustup update` already earlier this morning/

**Comment by svyatonik** [comment]
Most probably you're using stable clippy version then, which we are not using.

**Comment by adoerr** [comment]
Yep, that is it. Bit of a shame, since stable `clippy` do work well for me so far.

**Pull request merged**
