### PR TITLE
Match substrate's fmt

### LINKED ISSUE #1147: Change `fmt` to match `Substrate/Polkadot`
1. Use `rustfmt.toml` config from Substrate/Polkadot
2. Change CI to run `fmt +nightly`
3. Re-format the codebase.

Having a unified formatting will help with merges in the future.

### PR DESCRIPTION
**Pull request by hacpy**
Fix #1147.
I used substrate's fmt file according to your issue, then `cargo +nightly fmt`, and finally changed the ci, is there anything else wrong here?
Could I do that here? @tomusdrw

### CODE REVIEW

**Review by tomusdrw — APPROVED** [review]
lgtm, thanks a lot!

@svyatonik feel free to merge whenever you are comfortable with that also to avoid too many conflicts with your pending work.

**Comment by tomusdrw** [comment]
@TriplEight can we get `cargo-fmt` installed for `+nightly` in `paritytech/bridges-ci:production` image?

@hacpy can you take a look at the spellcheck failure? Should be easy to address and I believe it's caused by re-formatting.

**Comment by TriplEight** [comment]
@tomusdrw do you still need the stable `rustfmt` then?

**Comment by tomusdrw** [comment]
@TriplEight after this is merged = no, we don't need the stable one.

**Comment by TriplEight** [comment]
@tomusdrw here you go https://github.com/paritytech/scripts/pull/344
https://gitlab.parity.io/parity/infrastructure/scripts/-/pipelines/158145
The test will fail because there's no more `rustfmt` on stable and CI on master requires it, but for this PR you can add a debug line https://github.com/paritytech/parity-bridges-common/pull/1148/files#R18 and change the `CI_IMAGE`'s tag name to `staging`

**Pull request merged**
