### PR TITLE
Allow Root to assume SourceAccount.

### PR DESCRIPTION
**Pull request by kaichaosun**
Fixed https://github.com/paritytech/parity-bridges-common/issues/620

Another thing I notice is, [SourceRoot](https://github.com/paritytech/parity-bridges-common/blob/bf52fff13fbb1d3fc6a868d209cddddf2b8f79ef/relays/bin-substrate/src/cli/send_message.rs#L99) is not available in send_message CLI, is there an issue tracking this feature?

### CODE REVIEW

**Comment by svyatonik** [comment]
If you'll pass `--assume-account=<some-account>` using CLI, it won't pass the check you've altered in this PR, right? Because you may only pass this check (`verify_message_origin`) if the transaction signer is the same `source_account_id` from the `CallOrigin::SourceAccount()` OR if you're the root (that's what you've changed in this PR). But our CLI is not sending messages using root origin (as you've pointe), so this option seems unneeded now. Let's probably only leave your first commit (and `cargo fmt`)?

**Comment by kaichaosun** [comment]
I see, need to enable sudo call in CLI to support root origin call.

After some testing from polkadotjs/apps, the sudo call failed to pass the `pay_delivery_and_dispatch_fee` since [Root origin is not allowed to pay fee](https://github.com/paritytech/parity-bridges-common/blob/604eb1cd0941ba1e17d083fd198df1f19955abf8/modules/messages/src/instant_payments.rs#L77).
Does it make sense if I add an extra param `payer` for `send_message` dispatable, as Root origin from democracy/council is not supposed to hold assets from what I understand?

**Comment by svyatonik** [comment]
> Does it make sense if I add an extra param payer for send_message dispatable, as Root origin from democracy/council is not supposed to hold assets from what I understand?

Let's leave it for other PRs - there's a way now to configure that now (by changing that `RootAccount`) + there's #962 which will separate call origin from fee payer. Hopefully we'll be able to solve it in some general way

**Review by svyatonik — APPROVED** [review]

**Review by tomusdrw — APPROVED** [review]
Nice, thanks! I was suspecting this is going to be a bigger change, but the smaller the better 😅

**Pull request merged**
