### PR TITLE
update messages relay sequence diagram

### PR DESCRIPTION
**Pull request by cuteolaf**

### CODE REVIEW

**Review by svyatonik — COMMENTED** [review]
I don't see why it needs to be changed - that's for demonstrating that there may be lags in finality relay between two chains && we don't need to relay all headers. Do you have some other thoughts about it?

**Comment by cuteolaf** [comment]
@svyatonik Are you on Telegram?
I'd like to have a chat with you.

**Comment by svyatonik** [comment]
Better ask here, but if you really need a chat., you can reach me on [matrix](https://matrix.org/): `@svyatonik:parity.io`

**Comment by svyatonik** [comment]
Please reopen if you have some thoughts about it

**Pull request closed without merging**
